# Generated by Django 3.1.7 on 2021-04-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(default='undefined', max_length=100),
        ),
    ]
